services:
  postgres:
    container_name: INSTANT_db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - instant
    restart: unless-stopped

networks:
  instant:
    driver: bridge

volumes:
  postgres: