BEGIN;

CREATE TABLE IF NOT EXISTS chat_schema.groups
(
    chatid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    users INT[] NOT NULL,
    label TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS chat_schema.broadcasts
(
    messageid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chatid INT NOT NULL,
    ts BIGINT NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW())),
    body TEXT NOT NULL,
    sender INT NOT NULL
);

INSERT INTO chat_schema.groups (chatid, users, label)
SELECT 
    chatid,
    ARRAY[user1, user2] as users,
    label1 || ' & ' || label2 as label
FROM chat_schema.chats;

DO $$
DECLARE
    old_count INTEGER;
    new_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO old_count FROM chat_schema.chats;
    SELECT COUNT(*) INTO new_count FROM chat_schema.groups;
    
    IF old_count = new_count THEN
        RAISE NOTICE 'CHATS -> GROUPS: SUCCESS: % rows', old_count;
    ELSE
        RAISE EXCEPTION 'CHATS -> GROUPS: ERROR: old %, new %', old_count, new_count;
    END IF;
END $$;

INSERT INTO chat_schema.broadcasts (messageid, chatid, ts, body, sender)
SELECT 
    messageid,
    chatid,
    ts,
    body,
    sender
FROM chat_schema.messages;

DO $$
DECLARE
    old_count INTEGER;
    new_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO old_count FROM chat_schema.messages;
    SELECT COUNT(*) INTO new_count FROM chat_schema.broadcasts;
    
    IF old_count = new_count THEN
        RAISE NOTICE 'MESSAGES -> BROADCASTS: SUCCESS: % rows', old_count;
    ELSE
        RAISE EXCEPTION 'MESSAGES -> BROADCASTS: ERROR: old %, new %', old_count, new_count;
    END IF;
END $$;

DROP TABLE chat_schema.messages;
DROP TABLE chat_schema.chats;

COMMIT;