BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TYPE eventtype AS ENUM ('add_chat', 'upd_chat', 'del_chat', 'add_message', 'add_react', 'del_message', 'add_tie', 'upd_tie', 'del_tie', 'add_link', 'del_link', 'add_alert');
CREATE TYPE msgtype AS ENUM ('message', 'reaction');

ALTER TABLE auth_schema.alerts DROP COLUMN opened;

CREATE TABLE chat_schema.events
(
    eventid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    ts BIGINT DEFAULT (EXTRACT(EPOCH FROM NOW())) NOT NULL,
    type eventtype NOT NULL,
    chatid INT DEFAULT NULL,
    userid INT DEFAULT NULL,
    subid BIGINT DEFAULT NULL,
    content BYTEA DEFAULT NULL
);

ALTER TABLE chat_schema.ties ADD COLUMN eventid BIGINT DEFAULT nextval('chat_schema.events_eventid_seq'::REGCLASS);
ALTER TABLE chat_schema.ties DROP CONSTRAINT ties_pkey;
ALTER TABLE chat_schema.ties DROP COLUMN tieid;
ALTER TABLE chat_schema.ties ADD PRIMARY KEY (chatid, userid);

ALTER TABLE auth_schema.alerts ADD COLUMN eventid BIGINT DEFAULT nextval('chat_schema.events_eventid_seq'::REGCLASS);
ALTER TABLE auth_schema.alerts DROP CONSTRAINT alerts_pkey;
ALTER TABLE auth_schema.alerts DROP COLUMN alertid;
ALTER TABLE auth_schema.alerts ADD PRIMARY KEY (eventid);

ALTER TABLE chat_schema.broadcasts ADD COLUMN eventid BIGINT DEFAULT nextval('chat_schema.events_eventid_seq'::REGCLASS);
ALTER TABLE chat_schema.broadcasts DROP CONSTRAINT broadcasts_pkey;
ALTER TABLE chat_schema.broadcasts DROP COLUMN messageid;
ALTER TABLE chat_schema.broadcasts ADD PRIMARY KEY (eventid);

CREATE TABLE chat_schema.read
(
    readid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    ts BIGINT DEFAULT (EXTRACT(EPOCH FROM NOW())) NOT NULL,
    chatid INT REFERENCES chat_schema.groups(chatid) NOT NULL,
    userid INT REFERENCES auth_schema.users(id) NOT NULL,
    eventid BIGINT REFERENCES chat_schema.broadcasts(eventid) NOT NULL
);

ALTER TABLE chat_schema.broadcasts ADD COLUMN subid BIGINT DEFAULT NULL;
ALTER TABLE chat_schema.broadcasts ADD COLUMN type msgtype NOT NULL DEFAULT 'message'::msgtype;
ALTER TABLE chat_schema.broadcasts ADD COLUMN read BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE chat_schema.broadcasts ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE chat_schema.groups ADD COLUMN img TEXT NOT NULL DEFAULT ENCODE(E'\\x01'::BYTEA || gen_random_bytes(6), 'base64');
ALTER TABLE chat_schema.groups ADD COLUMN link TEXT DEFAULT NULL;

ALTER TABLE auth_schema.users ADD COLUMN img TEXT NOT NULL DEFAULT ENCODE(E'\\x01'::BYTEA || gen_random_bytes(6), 'base64');
ALTER TABLE auth_schema.users ADD COLUMN name TEXT NOT NULL DEFAULT 'User';

ALTER TYPE chatrole ADD VALUE 'queued';

INSERT INTO chat_schema.events (ts, type, chatid, userid, content)
SELECT
    0,
    'add_chat'::eventtype,
    chatid,
    NULL,
    convert_to(jsonb_build_object(
        'label', label,
        'img', img
    )::TEXT, 'UTF8')
FROM chat_schema.groups;

INSERT INTO chat_schema.events (eventid, ts, type, chatid, userid, content)
SELECT
    eventid,
    0,
    'add_tie'::eventtype,
    chatid,
    userid,
    role::TEXT::BYTEA
FROM chat_schema.ties;

INSERT INTO chat_schema.events (eventid, ts, type, chatid, userid, content)
SELECT
    eventid,
    ts,
    'add_message'::eventtype,
    chatid,
    sender,
    convert_to(body, 'UTF8')
FROM chat_schema.broadcasts;

INSERT INTO chat_schema.events (ts, type, userid, content)
SELECT
    ts,
    'add_alert'::eventtype,
    userid,
    convert_to(body, 'UTF8')
FROM auth_schema.alerts;

DO $$
DECLARE
    old_count INTEGER;
    new_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO old_count FROM chat_schema.groups;
    SELECT COUNT(*) + old_count INTO old_count FROM chat_schema.ties;
    SELECT COUNT(*) + old_count INTO old_count FROM chat_schema.broadcasts;
    SELECT COUNT(*) + old_count INTO old_count FROM auth_schema.alerts;
    SELECT COUNT(*) INTO new_count FROM chat_schema.events;
    
    IF old_count = new_count THEN
        RAISE NOTICE 'TABLES -> EVENTS: SUCCESS: % rows', old_count;
    ELSE
        RAISE EXCEPTION 'TABLES -> EVENTS: ERROR: old %, new %', old_count, new_count;
    END IF;
END $$;

CREATE OR REPLACE FUNCTION update_instant_state()
RETURNS TRIGGER AS $$
BEGIN
    CASE NEW.type::TEXT
        WHEN 'add_chat' THEN --
            INSERT INTO chat_schema.groups (chatid, label, img)
            VALUES (NEW.chatid, convert_from(NEW.content, 'UTF8')::JSONB->>'label', convert_from(NEW.content, 'UTF8')::JSONB->>'img');
        
        WHEN 'upd_chat' THEN --
            UPDATE chat_schema.groups
            SET label = convert_from(NEW.content, 'UTF8')::JSONB->>'label', 
                img = convert_from(NEW.content, 'UTF8')::JSONB->>'img'
            WHERE chatid = NEW.chatid;
        
        WHEN 'add_link' THEN --
            UPDATE chat_schema.groups
            SET link = convert_from(NEW.content, 'UTF8')
            WHERE chatid = NEW.chatid;
        
        WHEN 'del_link' THEN --
            UPDATE chat_schema.groups
            SET link = NULL
            WHERE chatid = NEW.chatid;
        
        WHEN 'del_chat' THEN --
            UPDATE chat_schema.groups
            SET deleted = TRUE
            WHERE chatid = NEW.chatid;
        
        WHEN 'add_tie' THEN --
            INSERT INTO chat_schema.ties (eventid, chatid, userid, role)
            VALUES (NEW.eventid, NEW.chatid, NEW.userid, convert_from(NEW.content, 'UTF8')::chatrole);
        
        WHEN 'upd_tie' THEN --
            UPDATE chat_schema.ties
            SET role = convert_from(NEW.content, 'UTF8')::chatrole,
                eventid = NEW.eventid
            WHERE chatid = NEW.chatid AND userid = NEW.userid;
        
        WHEN 'del_tie' THEN --
            DELETE FROM chat_schema.ties
            WHERE chatid = NEW.chatid AND userid = NEW.userid;
        
        WHEN 'add_message' THEN --
            INSERT INTO chat_schema.broadcasts (eventid, type, ts, chatid, sender, body)
            VALUES (NEW.eventid, 'message'::msgtype, NEW.ts, NEW.chatid, NEW.userid, convert_from(NEW.content, 'UTF8'));
        
        WHEN 'add_react' THEN --
            INSERT INTO chat_schema.broadcasts (eventid, subid, type, ts, chatid, sender, body)
            VALUES (NEW.eventid, NEW.subid, 'reaction'::msgtype, NEW.ts, NEW.chatid, NEW.userid, convert_from(NEW.content, 'UTF8'));
        
        WHEN 'del_message' THEN --
            UPDATE chat_schema.broadcasts 
            SET deleted = TRUE
            WHERE chatid = NEW.chatid AND eventid = NEW.subid;
            
            UPDATE chat_schema.broadcasts
            SET subid = (SELECT subid FROM chat_schema.broadcasts WHERE eventid = NEW.subid LIMIT 1)
            WHERE subid = NEW.subid;
        
        WHEN 'add_alert' THEN --
            INSERT INTO auth_schema.alerts (eventid, userid, body, ts)
            VALUES (NEW.eventid, NEW.userid, convert_from(NEW.content, 'UTF8'), NEW.ts);
    END CASE;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_state
    AFTER INSERT ON chat_schema.events
    FOR EACH ROW
    EXECUTE FUNCTION update_instant_state();

CREATE OR REPLACE FUNCTION update_read_state()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE chat_schema.broadcasts
    SET read = TRUE
    WHERE eventid = NEW.eventid;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_read
    AFTER INSERT ON chat_schema.read
    FOR EACH ROW
    EXECUTE FUNCTION update_read_state();

COMMIT;