DELETE FROM chat_schema.ties WHERE role = 'queued';
ALTER TYPE chatrole RENAME TO chatrole_obsolete;
CREATE TYPE chatrole AS ENUM ('admin', 'listener');
ALTER TABLE chat_schema.ties ALTER COLUMN role TYPE chatrole USING role::TEXT::chatrole;
DROP TYPE chatrole_obsolete;

ALTER TABLE chat_schema.groups DROP COLUMN img;

ALTER TABLE auth_schema.users DROP COLUMN img;

DROP TABLE chat_schema.read;

ALTER TABLE chat_schema.broadcasts DROP CONSTRAINT broadcasts_pkey;
ALTER TABLE chat_schema.broadcasts DROP COLUMN messageid;
ALTER TABLE chat_schema.broadcasts ADD COLUMN messageid BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE chat_schema.broadcasts ADD PRIMARY KEY (messageid);

DROP TABLE chat_schema.events;

DROP TYPE eventtype;